version: "3.6"

services:
  # More info at https://github.com/pi-hole/docker-pi-hole/ and https://docs.pi-hole.net/
  pihole:
    container_name: pihole
    hostname: 'pihole.homeserver.com'
    image: pihole/pihole:2022.12
    # For DHCP it is recommended to remove these ports and instead add: network_mode: "host"
    ports:
      - "53:53/tcp"
      - "53:53/udp"
    #  - "67:67/udp" # Only required if you are using Pi-hole as your DHCP server
      - "80:80/tcp"
    environment:
      TZ: 'Europe/Berlin'
      WEBPASSWORD: $PI_HOLE_PASSWORD
    # Volumes store your data between container upgrades
    volumes:
      - '$SERVICE_DIR/pihole/etc/pihole:/etc/pihole'
      - '$SERVICE_DIR/pihole/etc/dnsmasq.d:/etc/dnsmasq.d'
    #   https://github.com/pi-hole/docker-pi-hole#note-on-capabilities
    # cap_add:
    #   - NET_ADMIN # Required if you are using Pi-hole as your DHCP server, else not needed
    restart: unless-stopped
  
  jellyfin:
    image: lscr.io/linuxserver/jellyfin:10.8.8
    container_name: jellyfin
    hostname: 'jellyfin.homeserver.com'
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Berlin
      #- JELLYFIN_PublishedServerUrl=192.168.0.5 #optional
    volumes:
      - $SERVICE_DIR/jellyfin/library:/config
      - $SERVICE_DIR/jellyfin/tvseries:/data/tvshows
      - $SERVICE_DIR/jellyfin/movies:/data/movies
    ports:
      - 8096:8096
      - 8920:8920 #optional
      - 7359:7359/udp #optional
      - 1900:1900/udp #optional
    restart: unless-stopped
  
  gitlab:
    image: 'gitlab/gitlab-ee:15.7.0-ee.0'
    container_name: gitlab
    restart: always
    hostname: 'gitlab.homeserver.com'
    environment:
      GITLAB_OMNIBUS_CONFIG: |
        external_url 'http://gitlab.homeserver.com:8929'
        gitlab_rails['gitlab_shell_ssh_port'] = 2224
        gitlab_rails['initial_root_password'] = '$GITLAB_PASSWORD'
    ports:
      - '8929:8929'
      - '2224:22'
    volumes:
      - '$SERVICE_DIR/gitlab/config:/etc/gitlab'
      - '$SERVICE_DIR/gitlab/logs:/var/log/gitlab'
      - '$SERVICE_DIR/gitlab/data:/var/opt/gitlab'
    shm_size: '256m'
  
  postgres-db:
    container_name: postgres-db
    image: postgres
    restart: always
    volumes:
      - $SERVICE_DIR/postgres:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=$POSTGRES_DB
      - POSTGRES_USER=$POSTGRES_USER
      - POSTGRES_PASSWORD=$POSTGRES_PASSWORD

  nextcloud:
    image: nextcloud
    container_name: nextcloud
    restart: always
    ports:
      - 8080:80
    volumes:
      - $SERVICE_DIR/nextcloud:/var/www/html
    environment:
      - POSTGRES_HOST=postgres-db
      - POSTGRES_DB=$POSTGRES_DB
      - POSTGRES_USER=$POSTGRES_USER
      - POSTGRES_PASSWORD=$POSTGRES_PASSWORD
      - NEXTCLOUD_ADMIN_PASSWORD=$NEXTCLOUD_ADMIN_PASSWORD
      - NEXTCLOUD_ADMIN_USER=$NEXTCLOUD_ADMIN_USER
    depends_on:
      - postgres-db
